### ISSUE TITLE
[UPDATE] Latest change not publlished to pub.dev

### ISSUE THREAD

**Issue by blaqshyd** [venbrinoDev/chain_cli#2]
The README hasn't been updated on  [pub.dev](https://pub.dev/packages/chain_cli)

**Comment by venbrinoDev** [comment]
I will make the update on pub.dev

**Comment by blaqshyd** [comment]
Looking forward to it.

**Comment by venbrinoDev** [comment]
Hi @blaqshyd  i just updated the README file on pub.dev

**Comment by blaqshyd** [comment]
WTG 🚀🥂
